version: '2'
services:
  zookeeper:
    build: zookeeper
    ports:
      - "2181:2181"
  kafka:
#    image: registry.brandwatch-audiences.com/library/kafka:standalone-kafka-1.0.0-2
    build: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
